### ISSUE TITLE
缺少解析视频的文件

### ISSUE THREAD

**Issue by Joey-Lee** [6ag/EnglishCommunity-laravel#3]
报错如下：
FatalThrowableError in VideoController.php line 197:
Class 'App\Http\ParseVideo' not found

**Comment by Joey-Lee** [comment]
貌似ParseVideo.php是在.gitignore中给忽略了。

**Comment by 6ag** [comment]
是的，这个文件没有上传，敏感内容
涉及优酷视频解析算法，传播越多失效越快的

**Comment by Joey-Lee** [comment]
明白了。
